### ISSUE TITLE
can't run at the xp or winNT5.1

### ISSUE THREAD

**Issue by hchwork** [lstratman/EasyTabs#9]
can't run at the xp or winNT5.1
## 这个不能运行在xp操作系统上, 问题似乎是因为操作系统使用的dll中不存在现在调用的方法.

System.DllNotFoundException: Unable to load DLL 'dwmapi.dll': 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)
   at Win32Interop.Methods.Dwmapi.DwmExtendFrameIntoClientArea(IntPtr hWnd, MARGINS& pMarInset)
   at Stratman.Windows.Forms.TitleBarTabs.TitleBarTabs.SetFrameSize() in c:\Users\筹辉\Documents\GitHub.NETTitleBarTabs\TitleBarTabs.cs:line 343
   at Stratman.Windows.Forms.TitleBarTabs.TitleBarTabs.OnSizeChanged(EventArgs e) in c:\Users\筹辉\Documents\GitHub.NETTitleBarTabs\TitleBarTabs.cs:line 647
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at Stratman.Windows.Forms.TitleBarTabs.TitleBarTabs.WndProc(Message& m) in c:\Users\筹辉\Documents\GitHub.NETTitleBarTabs\TitleBarTabs.cs:line 697
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by bruce5794163** [comment]
那么怎么样去解决这个问题呢，我现在也遇到这样的问题啊。

**Comment by lstratman** [comment]
Sorry, XP is not a supported operating system for this library.
